sudo: false
dist: xenial
language: python
python:
- 3.6
- 3.7
- 3.8
matrix:
  include:
  - python: 3.8
    env: TOXENV=flake8
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success: coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: timbirk
  password:
    secure: H1MEew3qePw0SZ5TrqVTd9agYo7t+oOOBSkyXhVx2OLwQfrB0P+6EBm4I1l/iSVdKTkoCMkB1Kprqc9pN+1uHlbVw/35WNa071DfddwoQMBWRmK6zstDEsVyJ1XQEVTB3CIhBnRzZti1qLWmY3RmKFYHdXuvJSUNQPXtgy7rPY0yhdf0fbuNPiFykD8QJgt3NSjV9jOUz0mru9XiPxlFh/ehSXb0ZeIQUK1x/4ywR+p8n6ve4U3LY1WqJf/641ysrgFqWwuPjf5fj7AbrnKj2slHq6WMNulWdo/oDe1l4/ZjKcieRu5amLv4uZoJcq4x7FpQSU/hJv75kFYXJxXhnVOiLwVosfaKmvya3K6WwaFqW13KW+GBijXxHSchFNUhd8wnWPxgRl40OT9dvYB01HaB+xQQeBuID65mF9/zBA/fBGmlTrmWVT8z+UDqB7r5mncCLkb7PhlQQNhmNIASWt5fTf5A7aII2zEQ/h/q/EABJaFwaMWftaYk0ZBIDd0Ms4UJXmyZUxmB2XPe8AdYqJIHCCUdGlUZmEQCiM+Pd/joa/Ska2UBR/bnnxUH1FAOOERqaXk+8qlTkAYv3fHF7kvDKGA7IUSeMa9wQjR61Tk4Ifd5tuHfVT1fkZnGvBDF0VybFoy5oQmnURBr/izC7iY7IVFPb4NW7eJWsIjkTZA=
  on:
    tags: true
